spring:
   application:
     name: schedule-service
   config:
     import: "optional:configserver:http://localhost:8088"
   data:
     mongodb:
       uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster.co4s7.mongodb.net/
       authentication-database: admin
       database: schedule
   mail:
     host: smtp.gmail.com
     port: 587
     username: tatriet16@gmail.com
     password: qoaputtijsolpzxv
     properties:
       mail:
         smtp:
           auth: true
           starttls:
             enable: true