spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: "jdbc:mysql://localhost:3306/auth"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000
  security:
    user:
      name: ta_triet
      password: 123