spring:
  config:
    import: optional:configserver:http://config-server:8088
  cloud:
    config:
      uri: http://config-server:8088

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: prescription-service