spring:
   application:
     name: prescription-service
   config:
     import: "optional:configserver:http://localhost:8088"
   data:
     mongodb:
       uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster.co4s7.mongodb.net/
       authentication-database: admin
       database: prescription