server:
  port: 8060

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      uri: http://localhost:8060
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
#        - id: department-service
#          uri: lb://department-service
#          predicates:
#            - Path=/department/**


management:
  tracing:
    sampling:
      probability: 1.0