server:
  port: 8060

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      uri: http://localhost:8060
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/user/**
        - id: dental-service
          uri: lb://dental-service
          predicates:
            - Path=/dental/**
        - id: material-service
          uri: lb://material-service
          predicates:
            - Path=/material/**
        - id: dentist-service
          uri: lb://dentist-service
          predicates:
            - Path=/dentist/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/schedule/**


management:
  tracing:
    sampling:
      probability: 1.0