server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: patient-service
    profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8088}
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8088}
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:true}
      fail-fast: ${SPRING_CLOUD_CONFIG_FAILFAST:false}
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster.co4s7.mongodb.net/
      authentication-database: admin
      database: patient

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}